[package]
name = "dojo_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
bigdecimal = "0.4.5"
cairo-lang-macro = "0.1"
cairo-lang-syntax = "2.8.4"
cairo-lang-parser = "2.8.4"
cairo-lang-diagnostics = "2.8.4"
